# Available themes (commented out)
# theme: jekyll-theme-cayman
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate
# theme: jekyll-theme-architect
# theme: jekyll-theme-hacker
# theme: jekyll-theme-dinky
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine

# Active theme
theme: jekyll-theme-slate
